### ISSUE TITLE
Why use registers r15 to rbp?

### ISSUE THREAD

**Issue by ghosthamlet** [cfsamson/example-greenthreads#11]
There is just rsp used:  available.ctx.rsp = s_ptr.offset((size - 32) as isize) as u64,
so what is the usage of r15 to rbp?  I removed r15 - rbp in ThreadContext and the corresponding 'mov ...' in inline asm, the code still works fine.

**Comment by cfsamson** [comment]
I'm not sure what exactly what you mean, but only you're right in that only `rsp` is needed on the initial context switch, but to resume again you need to save off and restore the state of the rest of the "callee saved" registers as well since that is a "snapshot" of what the CPU is doing at that point which you need to pick up where you left off. 

If you can show me what you mean in [Rust Playground](https://play.rust-lang.org/) or something I might be able to give a better answer.

**Comment by cfsamson** [comment]
Funnily enough I tried what I think you suggested in the playground and it works. I think this is a consequence of the extremely simple code we use combined with how Rust generates instructions. 

There is no guarantee it will work when not saving all the registers, and you'll see this same implementation of saving off `r15` to `rbp`in all other implementations of green threads or fibers as well as in the x64-86 [psABI reference](https://github.com/hjl-tools/x86-psABI/wiki/X86-psABI) so it's the right thing to do.

**Comment by ghosthamlet** [comment]
Thanks for the fast reply, you are right, i got it now. What i suggested was like you said, this is the changed code: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=e4bdfc28ff9bac20d280d06861e16f0b

**Comment by cfsamson** [comment]
Closing this then since it's not something wrong :)
