### ISSUE TITLE
Question about stack pointer alignment guarantees

### ISSUE THREAD

**Issue by Veetaha** [cfsamson/example-greenthreads#12]
Hi, this is a splendid piece of knowledge you shared, great thanks, mate!

However, I have a question. I do am not a low-level programming pro, thus my thinking about it may not be relevant, if so, correct me, please!

So here is some background to the question:
According to `Background information` chapter:

> One more thing to note is that the stack alignment on x86-64 is 16 bytes. Just remember this for later.

Then in `An example we can build upon`:

```rust
fn main() {
    let mut ctx = ThreadContext::default();
    let mut stack = vec![0_u8; SSIZE as usize];
    let stack_ptr = stack.as_mut_ptr();

    unsafe {
        std::ptr::write(stack_ptr.offset(SSIZE - 16) as *mut u64, hello as u64);
        ctx.rsp = stack_ptr.offset(SSIZE - 16) as u64;
        gt_switch(&mut ctx);
    }
}
```
>  If our 48 byte stack starts at index 0, and ends on index 47, index 32 will be the first index of a 16 byte offset from the end of our stack.
> Make note that we write the pointer to an the offset of 16 bytes from the base of our stack (remember what I wrote about 16 byte alignment?).

So my question is doesn't the code you presented contain undefined behavior? From my perspective I see the following:
```
1. Let stack be equal to a new Vec which items are of u8 type and of length 48.
2. Let stack_ptr be the pointer to the beginning of stack.
3. Keep in mind that stack_ptr is a pointer to u8 which is not guaranteed to have 16-byte alignment.
4. Write the address of hello() function to memory at (stack_ptr + 32)
5. Keep in mind that (stack_ptr + 32) is not guaranteed to have 16-byte alignment.
7. Write to the real rsp register the value (stack_ptr + 32)
8. Boom! rsp contains a value that may not always be 16-byte aligned.
```
The code you wrote does work on my PC and on Rust Playground, but I still think that there is a bit of UB the code is playing with. Aren't we relying on the default allocator which returns maximum aligned memory blocks (i.e. the way `malloc()` works in C)? If so could you please add a note about that to the book or even amend the code to not rely on this, e.g. allocating `Vec<u128>` instead of `Vec<u8>`?

**Comment by cfsamson** [comment]
Hi and thanks for the feedback. Greatly appreciated! 

> Aren't we relying on the default allocator which returns maximum aligned memory blocks (i.e. the way malloc() works in C)?

You bring up a very good point. I actually considered mentioning this but I was a bit reluctant to add it since it warrants some extra explanation. In retrospect I think it might be important enough to spend a few sentences on.

I always recieved 16 byte aligned memory on all systems I tested on. However, as you say, what "guarantee" we actually have for that is uncertain and any proper implementation of this wil have a step where they make sure memory is aligned

I should also change this in the main example for the same reason you bring up here.

We could change the implementation in `main` to the code below, and add a small paragraph on why this is important (I omitted most of the comments here except the  new ones I added). 

The extra line where I test what happens if we get unaligned memory might be something to drop from the real example though.

What do you think?

```rust
fn main() {
    let mut ctx = ThreadContext::default();
    let mut stack = vec![0_u8; SSIZE as usize];

    unsafe {
    
         // this returns the pointer to the memory for our Vec. We offset it so we get the "high" address which will be the bottom of our stack
         let stack_bottom = stack.as_mut_ptr().offset(SSIZE);
         
         // change this to check what happens if we get memory which is not
         // aligned from our memory allocator
         let stack_bottom = (stack_bottom as usize + 3) as *mut u8;
         // make sure our stack itself is 16 byte aligned - it will always
         // offset to a lower memory address. Since we know we're at the "high"
         // memory address of our allocated space, we know that offsetting to
         // a lower one will be a valid address (given that we actually allocated
         // enough space to actually get an aligned pointer in the first place).
         let stack_bottom_aligned = (stack_bottom as usize &! 15) as *mut u8;
         
         // Sine we use such a small stack, if we get any offsets on our system
         // we might need to allocate som extra space (an additional 16 bytes
         // to allow for proper alignment)
         println!("Offset from `stack_bottom` to align to 16 bytes: {}", stack_bottom_aligned as isize - stack_bottom as isize);
       
        std::ptr::write(stack_bottom_aligned.offset(SSIZE - 32) as *mut u64, hello as u64);
        ctx.rsp = stack_bottom_aligned.offset(SSIZE - 32) as u64;
        gt_switch(&mut ctx);
    }
}
```

[Playground link to the suggested example](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=0970725fc4a190129f28d83c24a7b6e7)

**Comment by Veetaha** [comment]
@cfsamson, thank you for the clarification!
The solution you wrote seems fine if you want to show how to align not yet aligned pointers.
Maybe a bit better practice would to allocate `Vec<u128>` in the first place that will be already aligned or explicitly declare 16-byte aligned type and use `Vec<AlignedTo16>`;
```rust
#[repr(align(16)] struct AlignedTo16(u8);

let mut stack = vec![AlignedTo16(0); SSIZE / 16 as usize];
```
Though the option you proposed is also viable. And I'd recommend reducing the amount of casts for example here
```rust
 // let stack_bottom = (stack_bottom as usize + 3) as *mut u8;
let stack_bottom = stack_bottom.offset(3);
```

**Comment by cfsamson** [comment]
Thanks for the ideas. 

I do however think that using a `Vec<u8>` is easier to mentally parse since I already explain in detail how everything is set up using bytes in the text before and after the chapter. I'll have to go through a lot of the text to make sure everything still makes sense if I change that. 

Aligning the stack the way I did above is simply adding one line of code, which I can explain in a few sentences :)

**Comment by cfsamson** [comment]
I fixed the example here and I think I've covered all the relevant places in the book as well.
