### ISSUE TITLE
[Question] A little(maybe silly) question in "An example we can build upon" chapter

### ISSUE THREAD

**Issue by WindSoilder** [cfsamson/example-greenthreads#17]
Hi, very thanks for your great green threads book, I'm very enjoy it:)

I have a little question about this chapter:
https://cfsamson.gitbook.io/green-threads-explained-in-200-lines-of-rust/an-example-we-can-build-upon

regards to the hello function:
```rust
fn hello() {
    println!("I LOVE WAKEING UP ON A NEW STACK!");
    loop {}
}
```

I think the information which is needed to call `hello` is stored in the `stack` variable(in the specific stack position).  Am I right?

What if I have some code like this?
```rust
fn hello() {
    println!("I LOVE WAKEING UP ON A NEW STACK!");
    loop {
        hello()
    }
}
```

Does the `stack` variable still be used when I call `hello` recursively?

**Comment by cfsamson** [comment]
Thats great to hear.

I'm not 100% sure I understand your question correctly, but we store the address to `hello()` on the stack so when we `ret` (return) in the assembly code after setting `rsp` to point to our new stack it will pop of the address to `hello` and think that it's the return address from our `gt_switch` function. 

That means: 
```rust
1: fn hello() {
2:   println!("I LOVE WAKEING UP ON A NEW STACK!");
3:    loop {
4:        hello()
5:    }
6: }
```

Would first call `hello` as a result of the `ret` in `gt_switch`, then print out the message the next thing that would happen is this in step 4:

1. call `hello` which pushes the current stack pointer on to the stack as a return address
2. return from `hello` (pop the address we pushed onto the stack
3. `goto` line `3`
4. Repeat process of pushing the return address to the stack and popping it again when we return from `hello`

Now, this only adds a little extra to the stack since we `push` and `pop` the same address, but in a deep recursion you would continuously `push` return addresses onto the stack until you finally start returning and thereby popping of the stack again. If this recursion is too deep, you end up exhausting the whole stack by pushing return addresses on to it leading to a stack overflow.

That said, since we use an extremely small stack in the example (so we can print out the whole stack) you can cause a stack overflow just by pushing the extra address, but you should see it run as expected in a loop if you increase the `STACK_SIZE` sufficiently.

**Comment by WindSoilder** [comment]
Thanks for your reply :)
Regards to this:
> Now, this only adds a little extra to the stack since we `push` and `pop` the same address, but in a deep recursion you would continuously `push` return addresses onto the stack until you finally start returning and thereby popping of the stack again.

I'm confused what stack we push to?  Is the extrememly small stack defined by *ourself* in the main function?  Or just a system allocated stack for the process.

**Comment by cfsamson** [comment]
No problem. I first misread the code a bit so please check my updated response above. In this case we push to the extremely small stack we created ourselves since we "returned into" that stack in `gt_switch`. Remember that we set `rsp` to an address of our new stack before `ret` so any push/pop will happen relative to the "current stack top" pointed to by `rsp` (on our new stack).

**Comment by WindSoilder** [comment]
Thanks very much! I understand it now :)
