### ISSUE TITLE
stack pointer is not 16-bytes aligned when `guard()` starts running

### ISSUE THREAD

**Issue by ziyi-yan** [cfsamson/example-greenthreads#19]
As it said in the book,

> One more thing to note is that the stack alignment on x86-64 is 16 bytes. Just remember this for later.

so here [we set up a 16-bytes alignment stack](https://github.com/cfsamson/example-greenthreads/blob/master/src/main.rs#L128) for `f()` to use.

However, when `f()` finish and `ret` to `guard()`, the stack is not 16-bytes aligned anymore and it could cause segmentation fault when we use something complex in our code (something has [SSE instructions](https://stackoverflow.com/questions/49391001/why-does-system-v-amd64-abi-mandate-a-16-byte-stack-alignment#comment85783490_49391001) can cause the problem). Thanks for @austaras who found this problem while [extending this example](https://github.com/Austaras/green-threads) to leverage multi-threads. Here is a [commit](https://github.com/ziyi-yan/green-threads/commit/1a231abfef3318ea2ae70c3ed1423d5ff5b04017) which could reproduced the segmentation fault.

In the [commit](https://github.com/ziyi-yan/green-threads/commit/f83ea198a93ec59e2d5e7b7de57c45b75a4b7dee) to solve the problem, I put the address of `guard()` to a 16-bytes aligned place too. And I use an empty `skip()` function, which only contains one `ret` instruction, to skip 8 bytes on stack and handle the execution from `f()` to `guard()`. In this way, we can have a aligned stack for `guard()` now.

Btw, I really enjoy your book and learned a lot about x86-64 assembly and how those registers works. Thanks!

**Comment by cfsamson** [comment]
That's a really good catch. Seems I didn't remember my own advice when writing the example. I'll have to double-check what the best way to handle this is (your solution sounds nice and is easy to understand, though) and re-test on both linux and macos (and Windows) when I have a little time. I'll get back to this and correct the book as well.

Can you confirm that your fix works in both debug and `--release` builds? Do you run linux or macos?

Thanks for reporting, and I'm glad to hear you enjoyed the book 👍

**Comment by ziyi-yan** [comment]
I run it on macOS with `rustc 1.46.0-nightly (346aec9b0 2020-07-11)`. I confirmed that the fix can work both on debug and release.

**Comment by cfsamson** [comment]
Thanks. I'll get back to this issue when I have a little more time to re-test and rewrite the relevant parts.

**Comment by cfsamson** [comment]
@ziyi-yan This was a great catch, really. I checked it on all platforms and it works as expected. I also think the solution of using a `skip` function is the simplest way of solving this (all the other solutions I came up with ended up adding quite a bit of complexity).

I've updated all the examples and the relevant parts of the book. I've credited you in the readme changelog, and in the changelog of the book.

**Comment by Daniel-Xu** [comment]
@ziyi-yan @cfsamson hi, guys, I'm new to assembly, I'm confused about `16 bytes alignment`, would you plz help me to clarify it? 

1. Do we need to align all stuff at 16 bytes? (all data, addresses, for example `skip` is not 16 bytes aligned) 
2. from the abi: In other words, the stack needs to be 16 (32 or 64) byte aligned immediately before the call instruction is executed.  Does this controdict to the PR?

**Comment by cfsamson** [comment]
@Daniel-Xu I'll try to answer your questions:

1. You have to align the base of the stack and every stack frame to 16 bytes. `skip` is not a normal function call, since it's marked as a "naked" function. This means it behaves radically different from what you expect from a normal function. In this case, it's better not to think of `skip` as a function in the sense of requiring to comply with any ABI. When the CPU fetches the instructions pointed to by the address `skip`, it only gets a `ret` instruction - which pops of the next value of the stack into the instruction pointer register in which the CPU will run the instructions at that location.
2. No, as mentioned above. Naked functions does not execute any `call` instruction or set up any new stack frames, unless you explicitly do it yourself.

Just for some context. The ABI requirements are there so that the compiler for a specific architecture can make certain assumptions about how the stack is laid out. The reason both Windows and Unix both require 16 byte alignment on x86_64 targets, besides of having to set some rules for compilers to follow, is that some instructions requires to be called at 16 byte boundaries. The most frequent example is SIMD instructions like `moveaps` and the like. For these instructions, a 16 byte alignment is a hardware requirement, so it's likely chosen as an ABI requirement for that reason.

A `naked` function isn't really a "function". The compiler basically assumes nothing about the naked functions themselves, and it's up to the programmer to make sure you don't violate the ABI requirements. Calling `ret` from a non-aligned stack pointer is allowed (it's actually pretty common, since a `call` instruction with an aligned stack pointer, will push the return address to the stack making the return address unaligned, and when the "called" instruction calls `ret` when done it pops the unaligned return address off the stack and resumes execution from whatever instructions the return address points to).

I hope this makes things a bit clearer.

**Comment by Daniel-Xu** [comment]
> @Daniel-Xu I'll try to answer your questions:
> 
> 1. You have to align the base of the stack and every stack frame to 16 bytes. `skip` is not a normal function call, since it's marked as a "naked" function. This means it behaves radically different from what you expect from a normal function. In this case, it's better not to think of `skip` as a function in the sense of requiring to comply with any ABI. When the CPU fetches the instructions pointed to by the address `skip`, it only gets a `ret` instruction - which pops of the next value of the stack into the instruction pointer register in which the CPU will run the instructions at that location.
> 2. No, as mentioned above. Naked functions does not execute any `call` instruction or set up any new stack frames, unless you explicitly do it yourself.
> 
> Just for some context. The ABI requirements are there so that the compiler for a specific architecture can make certain assumptions about how the stack is laid out. The reason both Windows and Unix both require 16 byte alignment on x86_64 targets, besides of having to set some rules for compilers to follow, is that some instructions requires to be called at 16 byte boundaries. The most frequent example is SIMD instructions like `moveaps` and the like. For these instructions, a 16 byte alignment is a hardware requirement, so it's likely chosen as an ABI requirement for that reason.
> 
> A `naked` function isn't really a "function". The compiler basically assumes nothing about the naked functions themselves, and it's up to the programmer to make sure you don't violate the ABI requirements. Calling `ret` from a non-aligned stack pointer is allowed (it's actually pretty common, since a `call` instruction with an aligned stack pointer, will push the return address to the stack making the return address unaligned, and when the "called" function calls `ret` when it's done it pops the unaligned return address off the stack and resumes execution from whatever instructions the return address points to).
> 
> I hope this makes things a bit clearer.

Thanks for the reply. It clears my confusion.
