### ISSUE TITLE
Possibly safer implementation 1

### ISSUE THREAD

**Issue by cfsamson** [cfsamson/example-greenthreads#5]
Reddit comment: https://www.reddit.com/r/rust/comments/bzp0cz/green_threads_explained_in_200_lines_of_rust/eqxxkxh/

`I think vec![0_u8; SSIZE as usize]; can be refactored into vec![0_u8; SSIZE as usize].into_boxed_slice(); at which point all your issues with vectors reallocating themselves go away because you cannot grow the slices.`

Combined with using `to_ne_bytes()` instead of pointer casting could make it safer.

Check and see if this is really any safer or makes the main content of the code harder to parse for readers.

**Comment by daboross** [comment]
If it turns out better to continue using `Vec<u8>`, maybe `Box<[u8]>` could be mentioned in [this paragraph](https://cfsamson.gitbook.io/green-threads-explained-in-200-lines-of-rust/simple-but-unsafe-green-thread-implementation)?

> The important thing to note is that once a stack is allocated it must not move! No `push()` on the vector or any other methods that might trigger a reallocation. In a better version of this code we would make our own type that only exposes the methods we consider safe to use.

**Comment by cfsamson** [comment]
Yes, that's actually a very good alternative. The think I'm most worried about is the amount of code needed to safely write a [u8;8] that's returned from `to_ne_bytes()` to the slice at a specified position. If it makes the code in the `spawn` method significantly longer I'm not sure it's worth it, and it's better to mention it in the text.

**Comment by daboross** [comment]
If we use the `byteorder` crate and a trick to make the array a writer, I think writing code should still be pretty concise?

It's arguably more confusing than just using `ptr::write`, but this should technically work:

```rust
use std::io::Write;
use byteorder::{NativeEndian, WriteBytesExt};

(&mut arr[(size - 8) as usize..])
    .write_u64::<NativeEndian>(guard as u64);
```
([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b4b15b12df286116f454c6d356f76673))

It exploits the fact that `&mut [u8]` implements `Write`. I think it's allowed on `&mut [u8]` because the pointer can be modified to point to point to a later place in the array after writing the bytes.

I'm not sure if I'd actually choose to write this over `ptr::write`. Though maybe it'd be worth it to make a second less unsafe version of the example which could be a little less clear in favor of being slightly more checked?

**Comment by cfsamson** [comment]
Thanks for checking this out. I'm leaning towards the latter. The `byteorder` crate uses `unsafe` all over the place to do basically the same as we do here so what we in practice do is to exchange one unsafe implementation with just a better vetted one, makes sense for production code but it's still unsafe, better to make it explicit here I think than to hide it.

**Comment by cfsamson** [comment]
I added a paragraph about this in the section suggested by @daboross. Thanks for the help.
