### ISSUE TITLE
On Windows, XMM6 through XMM15 must be preserved

### ISSUE THREAD

**Issue by kccqzy** [cfsamson/example-greenthreads#6]
According to [Microsoft docs](https://docs.microsoft.com/en-us/cpp/build/x64-software-conventions?view=vs-2019) the XMM6 through XMM15 registers are non-volatile, i.e. callee-saved. So for the function to work properly on Windows, we need a bunch of `movdqu` in the `switch` function.

**Comment by kccqzy** [comment]
Wait, I don't think the code is meant to run on Windows…

**Comment by cfsamson** [comment]
@kccqzy It works on Linux, Windows and Mac (there was quite some small details to take care of to make sure it did), you are right however. They are callee saved and I just linked to the psABI documentation. It works (i assume) since we don't use any floating point registers or SIMD instructions (which of course could be changed in the future by the compiler) so the right thing is probably to point it out and leave a link to the relevant windows reference to point people in the right direction.
